### ISSUE TITLE
Getting documentation cross-links to work

### ISSUE THREAD

**Issue by gergondet** [jrl-umi3218/jrl-cmakemodules#104]
Hi,

Has anyone using the jrl-cmakemodules in combination with jrl-travis managed to get the cross-links between projects to work?

In my case, I've setup the proper TAGFILES entries in the [RBDyn](https://github.com/jrl-umi3218/RBDyn) repository but in the online [doc](https://jrl-umi3218.github.io/RBDyn) the links to the SpaceVecAlg library (e.g. click sva::RBInertiad on this [page](http://jrl-umi3218.github.io/RBDyn/doxygen/HEAD/a00002.html#aa7930e0bb454b55c51742130eb366aa8)) are definitely not correct. Part of the problem seems to be that doxygen does not generate any `installdox` script in my case but I'm not sure why...

I think this issue is somewhat related to #3 but I'm having trouble to get this feature to work even with a single TAGFILE entry. One possibility I see is to not rely on `installdox` and simply sed the local links to a generally correct github url (e.g. for a project organization/repo replace $install_dir/share/doc/repo/doxygen-html by organization.github.io/repo/doxygen/HEAD) based on the entries in a new argument to the `update-doxygen-doc.sh` script.

**Comment by jmirabel** [comment]
At https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/github/update-doxygen-doc.sh#L315
```
for doxytag in $installdox_args; do
	url=`echo "$installdox_urls" | cut -d' ' -f$i`
	./installdox.fixed -q -l ${doxytag}.doxytag@$url \
	    2> /dev/null > /dev/null \
	    || true
	i=$((i+1))
done
```

Did you try to add `SpaceVecAlg` informations to variables `installdox_args` and `installdox_urls` at the beginning of the same file ?

**Comment by gergondet** [comment]
I didn't yet but I don't even enter this part of the code (see [this travis log](https://travis-ci.org/jrl-umi3218/RBDyn/jobs/174692187)]) as I don't have an `installdox` script generated by doxygen.

**Comment by jmirabel** [comment]
The script seems to be properly run. Not far from the end of the travis raw log:

```
+/home/travis/build/jrl-umi3218/RBDyn/cmake/github/update-doxygen-doc.sh -r /home/travis/build/jrl-umi3218/RBDyn -b /tmp/_ci/build
* Checkout HEAD...
* Generating the documentation...
* Creating the temporary directory...
* Clone the project...
* Copy the documentation...
* Generate the commit...
* Push the generated commit...
To https://#EDITED#:#EDITED#@github.com/jrl-umi3218/RBDyn
   d83056d..84704f9  gh-pages -> gh-pages
Documentation updated with success!
```

**Comment by jmirabel** [comment]
I understand what you mean now. The `installdox` is not generated because:
```
# TAGFILES = file1=loc1 "file2 = loc2" ...
# where "loc1" and "loc2" can be relative or absolute paths or
# URLs. If a location is present for each tag, the installdox tool
# does not have to be run to correct the links.
```

To correct your links, either:
- remove `@SPACEVECALG_DOXYGENDOCDIR@` in your `Doxyfile.extra` and an `installdox` should be generated.
- change `@SPACEVECALG_DOXYGENDOCDIR@` to the correct url when on travis.

The second option would be a nice addition to the cmake module.

**Comment by gergondet** [comment]
Ah, ok, I understand now. Since `SPACEVECALG_DOXYGENDOCDIR` is found through pkg-config I guess we have to work out a way to get the second option working (since this works fine when building locally). I'll look into that.

**Comment by jmirabel** [comment]
I just tried on another project. I removed the url in my `Doxyfile.extra` but it does not generate a `installdox`.
The second option should work.

**Comment by jmirabel** [comment]
From Doxygen's changelog (https://www.stack.nl/~dimitri/doxygen/manual/changelog.html):
> # Release 1.8.0
> (release date 25-02-2012)
> ...
> The tool doxytag has been declared obsolete and is removed (it wasn't working properly anyway). Same goes for the installdox script.
