### ISSUE TITLE
Compilation flags from pkg-config are quoted with spaces

### ISSUE THREAD

**Issue by haudren** [jrl-umi3218/jrl-cmakemodules#106]
I was building a project, and decided to update the jrl-cmakemodules. Immediately, the build broke in Release mode, but not in Debug mode.

The reason is that in one of the depending .pc we have this line:
```
Cflags:  -I${includedir} -I/usr/include -DBOOST_SYSTEM_NO_DEPRECATED
```
Then, the generated compile command when using the Release mode contains:
```
-isystem /usr/include/libdrm    " -DBOOST_SYSTEM_NO_DEPRECATED"
```
Which obviously fails with:
```
clang: error: no such file or directory: ' -DBOOST_SYSTEM_NO_DEPRECATED'
```

While in Debug mode:
```
-isystem /usr/include/libdrm    "-DBOOST_SYSTEM_NO_DEPRECATED "
```
And this works.

This leads me to believe that cflags should *not* be enclosed in quotes, or trimmed beforehand. A simple fix is to remove this line (pkg-config.cmake:674):
```cmake
STRING(REPLACE ";" " " CFLAGS "${CFLAGS}")
```

However, this operation is supposed to be necessary for "old" CMake, but I am running 2.8.12: is it really necessary?

**Comment by jmirabel** [comment]
This has been introduced not so long ago by #101

**Comment by haudren** [comment]
Do you remember for which versions is this necessary ? I've also tried trimming a few strings, but it didn't yield the desired result.

**Comment by jmirabel** [comment]
I don't know. @jcarpent may know.
Could it be replaced by the following ?
```cmake
FOREACH(FLAG ${CFLAGS})
  SET(TMP ${TMP} " " ${FLAG})
ENDFOREACH(FLAG ${CFLAGS})
SET(CFLAGS ${CFLAGS})
```
This does not put quotes around flags.

**Comment by jcarpent** [comment]
The last proposition of @jmirabel seems to work.

**Comment by haudren** [comment]
Hum, I just tried on a quite big project, and I had to kill CMake after a good minute of processing... This was of course almost instantaneous before. Not sure if I fell into an infinite loop, or if appending in this way to a list is just way too slow. Note that I had slightly modified the code like so (I think this was your intent):
```cmake
FOREACH(FLAG ${CFLAGS})
    SET(TMP ${TMP} " " ${FLAG})
ENDFOREACH(FLAG ${CFLAGS})
SET(CFLAGS ${TMP})

SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ${COMPILE_OPTIONS_NAME} ${CFLAGS}")
```

**Comment by jmirabel** [comment]
I would be very surprised indeed that it causes an infinite loop or that it is so this slow. I would call that a bug in cmake.
Is the big project freely accessible somewhere ? At list the CMakeLists.txt(s)
I guess it is easy to know if it really is the issue. Did you try to set a huge "CFLAGS" for testing purposes and to copy it the two ways ? Or just to print the content of CFLAGS before copying it ?

**Comment by haudren** [comment]
Yes I was very surprised too... This project is an internal, private project, but I can probably try to construct a minimal example from it.

**Comment by haudren** [comment]
Ok so the cflags are simply:
```
$<$<CONFIG:Debug>:-DBOOST_SYSTEM_NO_DEPRECATED>$<$<NOT:$<CONFIG:Debug>>:-DBOOST_SYSTEM_NO_DEPRECATED>
```

But then, the first few iterations of the Cflags are:
```
1: $<$<CONFIG:Debug>:-DBOOST_SYSTEM_NO_DEPRECATED>
2: $<$<CONFIG:Debug>:-DBOOST_SYSTEM_NO_DEPRECATED> $<$<NOT:$<CONFIG:Debug>>:-DBOOST_SYSTEM_NO_DEPRECATED>
3: $<$<CONFIG:Debug>:-DBOOST_SYSTEM_NO_DEPRECATED> $<$<NOT:$<CONFIG:Debug>>:-DBOOST_SYSTEM_NO_DEPRECATED>
4: $<$<CONFIG:Debug>:-DBOOST_SYSTEM_NO_DEPRECATED> $<$<NOT:$<CONFIG:Debug>>:-DBOOST_SYSTEM_NO_DEPRECATED>
5: $<$<CONFIG:Debug>:-DBOOST_SYSTEM_NO_DEPRECATED> $<$<NOT:$<CONFIG:Debug>>:-DBOOST_SYSTEM_NO_DEPRECATED>
6: $<$<CONFIG:Debug>:-DBOOST_SYSTEM_NO_DEPRECATED> $<$<NOT:$<CONFIG:Debug>>:-DBOOST_SYSTEM_NO_DEPRECATED>   $<$<CONFIG:Debug>:-DBOOST_SYSTEM_NO_DEPRECATED>
```

Note, the patch I used to test:
```diff
-  STRING(REPLACE ";" " " CFLAGS "${CFLAGS}")
+  #STRING(REPLACE ";" " " CFLAGS "${CFLAGS}")
+
+  message("CFLAGS :")
+  message(${CFLAGS})
+  message("XXXXXXX")
+
+  FOREACH(FLAG ${CFLAGS})
+    SET(TMP ${TMP} " " ${FLAG})
+    message("TMP: ")
+    message(${TMP})
+    message("###")
+  ENDFOREACH(FLAG ${CFLAGS})
+  SET(CFLAGS ${TMP})
+
+  message("CFLAGS :")
+  message(${CFLAGS})
+  message("XXXXXXX")
```

**Comment by jmirabel** [comment]
Can you put a `SET(TMP)` before the `FOREACH` loop?

**Comment by jmirabel** [comment]
If I count well, `$TMP` is just not reset.

1. first `message(${CFLAGS})`
2. `message(${TMP})` first iteration
3. `message(${TMP})` second iteration
4. second `message(${CFLAGS})` (same as last `$TMP`)
5. first `message(${CFLAGS})` when calling the same code.
2. `message(${TMP})` first iteration

**Comment by haudren** [comment]
Indeed, you are right! However, one also has to remove the `" "` in the SET:
```cmake
  #STRING(REPLACE ";" " " CFLAGS "${CFLAGS}")

  SET(TMP)
  FOREACH(FLAG ${CFLAGS})
    SET(TMP ${TMP} ${FLAG})
  ENDFOREACH(FLAG ${CFLAGS})
  SET(CFLAGS ${TMP})
```

**Comment by jmirabel** [comment]
Without `" "`, I'm not sure @jcarpent original problem will be solved. @jcarpent, can you try ?

And actually, even in your case, it works because you have only one flag in the end (after cmake processed the debug variable). What if you have two ? I suspect you won't have a space between the two and this will lead to an error.

**Comment by jmirabel** [comment]
What is the issue with the `" "` ?

**Comment by jmirabel** [comment]
Also, if you do a pull-request to patch your issue, I think it should be enclosed in a
```cmake
IF(${CMAKE_VERSION} VERSION_LESS 2.8.12)
   ...
ENDIF(${CMAKE_VERSION} VERSION_LESS 2.8.12)
```
I guess you would not have had the issue if it had already been the case.

@jcarpent problem was on old CMake versions. Newer versions of CMake do it better than we do.

**Comment by haudren** [comment]
With the `" "`:
```
-isystem /usr/include/libdrm    " " -DBOOST_SYSTEM_NO_DEPRECATED
```
is generated, and of course crashes with:
```
c++: error:  : No such file or directory
```
For my version at least, everything works just fine if we remove the `STRING(REPLACE ...` instruction, i.e. this patch would do:
```
diff --git a/pkg-config.cmake b/pkg-config.cmake
index 5f9eb9e..f7a45b5 100644
--- a/pkg-config.cmake
+++ b/pkg-config.cmake
@@ -671,7 +671,10 @@ MACRO(PKG_CONFIG_USE_LCOMPILE_DEPENDENCY TARGET PREFIX)
     ENDFOREACH()
   ENDIF()
   # This cast from LIST to STRING is mandatory for old CMake versions
-  STRING(REPLACE ";" " " CFLAGS "${CFLAGS}")
+  if(${CMAKE_VERSION} VERSION_LESS 2.8.12)
+    STRING(REPLACE ";" " " CFLAGS "${CFLAGS}")
+  endif(${CMAKE_VERSION} VERSION_LESS 2.8.12)
+
   SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ${COMPILE_OPTIONS_NAME} "${CFLAGS}")
 
   # Include/libraries paths seems to be filtered on Linux, add paths
```

**Comment by jmirabel** [comment]
> With the " ":
> 
> ```-isystem /usr/include/libdrm    " " -DBOOST_SYSTEM_NO_DEPRECATED```
> 
> is generated, and of course crashes with:
> 
> ```c++: error:  : No such file or directory```

CMake version 3.2.2 does not do this. Something must have changed in between. As it is intended to old CMake versions, your snippet is the one we should use.

**Comment by jcarpent** [comment]
I do not have time to check on older Cmake versions, but I think the issues can be fixed by the patch proposed by @haudren.
PS: on the Romeo robot, the cmake version is still 2.8.11. It would be nice if the Cmake modules can be compatible with old Cmake version.

**Comment by jmirabel** [comment]
:+1: for `if(${CMAKE_VERSION} VERSION_LESS 2.8.12)`.

**Comment by haudren** [comment]
@jcarpent : Thanks for the insight... Thankfully on our end we do not have that problem, I hope it won't cause problems (if it does, I'll strive to find another workaround).

I'll submit a PR.
