### ISSUE TITLE
Compilation Check of Eigen Version

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/jrl-cmakemodules#109]
I started getting runtime crashes without any other indications that were caused by my eigen version changing while Tasks, rbdyn, sva, etc were not recompiled. Ceres has a mechanism to prevent this I think would be worthwhile to add here and to the appropriate libraries.

- [The error ceres reports in CeresConfig.cmake](https://github.com/ceres-solver/ceres-solver/blob/523e397be2c7820e2b1979886eaad2df9b466d40/cmake/CeresConfig.cmake.in#L217)
- [The configure_file call to set the appropriate variables](https://github.com/ceres-solver/ceres-solver/blob/master/cmake/CreateCeresConfig.cmake#L113)

**Comment by jmirabel** [comment]
The `find_package` command can be passed the option `EXACT`, described as this in the doc:

> The [version] argument requests a version with which the package found should be compatible (format is major[.minor[.patch[.tweak]]]). The EXACT option requests that the version be matched exactly. If no [version] and/or component list is given to a recursive invocation inside a find-module, the corresponding arguments are forwarded automatically from the outer call (including the EXACT flag for [version]). Version support is currently provided only on a package-by-package basis (details below).

Isn't this sufficient ?

**Comment by ahundt** [comment]
> Isn't this sufficient ?

The EXACT option is for a different use case when only exactly one version of eigen (or any library) is supported. 

In this use case the code supports multiple versions of eigen correctly at compile time, but you can't change the version unless you recompile. In other words, if the code is installed with one version of eigen and then the installed eigen version subsequently changes, there will be a mismatch leading to crashes.

**Comment by ahundt** [comment]
as explained on the linked line:

>"Found Eigen dependency, but the version of Eigen "
      "found (${EIGEN_VERSION}) does not exactly match the version of Eigen "
      "Ceres was compiled with (${CERES_EIGEN_VERSION}). This can cause subtle "
      "bugs by triggering violations of the One Definition Rule. See the "
      "Wikipedia article http://en.wikipedia.org/wiki/One_Definition_Rule "
      "for more details"

**Comment by jmirabel** [comment]
I know what you mean but they could replace line:
```
find_package(Eigen ${CERES_EIGEN_VERSION} QUIET)
```
by
```
find_package(Eigen ${CERES_EIGEN_VERSION} EXACT)
```
to have the same behaviour.

**Comment by jmirabel** [comment]
But I agree that to do this, you need a way of passing `PKG_EIGEN_VERSION` variable. This could be done by pkg-config or by Config.cmake.

The issue with adding `find_package(Eigen...)` in `Config.cmake` automatically is that packages that need Eigen only at compile time (only in `.cc` files, and not in headers) will require any downstream user to have Eigen (with a specific version), which is too restrictive.

One option is to fill a list `EIGEN_VERSION_OF_DEPENDENCIES` for each `ADD_*_DEPENDENCY` which depends on Eigen and check each element of this list against `Eigen_VERSION` in a `SETUP_PROJECT` submacro, when Eigen was found.

My prefered option is still the following manual option: add `PKGa_EIGEN_VERSION` in pkg-config file of PKGa. Then in PKGb, do
```cmake
ADD_REQUIRED_DEPENDENCY(PKGa)
SEARCH_FOR_EIGEN("Eigen = ${PKGa_EIGEN_VERSION}")
```

PS: `SEARCH_FOR_EIGEN` does not check the version when looking for Eigen without pkg-config. I think this is a bug.
