### ISSUE TITLE
[CMake] Installing .pyc files

### ISSUE THREAD

**Issue by nim65s** [jrl-umi3218/jrl-cmakemodules#136]
Hi,

In https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/python.cmake#L274 we try to install .pyc files.

First of all, I don't understand why.
Does someone have an explanation ?

Then, in python 3.2+, [PEP 3147](https://www.python.org/dev/peps/pep-3147/) states that compiled files are no more `$filename.pyc`, but `__pycache__/$filename.<magic>.pyc` with `<magic>` something like `cpython-35`, so cmake will not find `$filename.pyc`

This issue follows https://github.com/stack-of-tasks/pinocchio/issues/464

**Comment by jmirabel** [comment]
>  so cmake will not find $filename.pyc

That isn't true since it is compiled with `py_compile.compile` (https://docs.python.org/3/library/py_compile.html#py_compile.compile) and that the name of output file is specified manually.

However, the installed file will not be used as the naming convention does not follow the above mentioned standard.

I see two options:
- do not install the compiled files when using Python >= 3.2,
- do not install the compiled files at all.

I highly prefer the second as it does not complicate the code. Moreover, as @nim65s suggests, I think it is not relevant to install the compiled version.

**Comment by gergondet** [comment]
> First of all, I don't understand why.
> Does someone have an explanation ?

I would have guessed this was for packaging purpose but that's actually against [Debian Python policy]( https://www.debian.org/doc/packaging-manuals/python-policy/module_packages.html#byte_compilation) and the compilation is handled in the post-installation phase. Maybe @thomas-moulard has some recollection of why he introduced this feature.

However, I agree this seems reasonable simply not to do it anymore.

**Comment by jmirabel** [comment]
There is also a third version: let `py_compile.compile` create the compiled file with the default name and install this file.

**Comment by nim65s** [comment]
Based on what is done by debian (cf. @gergondet 's link) and [robotpkg](https://git.openrobots.org/projects/robotpkg/repository/revisions/master/entry/mk/sysdep/python.mk#L261), I think that installing .pyc / .pyo should be let to the package manager.  So we don't need to do this.

**Comment by jcarpent** [comment]
@nim65s What is the current status of this discussion?

**Comment by nim65s** [comment]
It looks like we all agree on not installing `.pyc` files. 

On my side, in most packages on robotpkg, there are no `.pyc` files, as the macro `PYTHON_INSTALL_BUILD` is not used: python files are usually either installed with `INSTALL` or compiled as a check or as an util in the build directory with `PYTHON_BUILD`.

So from my point of view, `PYTHON_INSTALL_BUILD` is just dead code that should be removed, but someone else might be using it.

**Comment by nim65s** [comment]
Well… In fact, `PYTHON_INSTALL_ON_SITE` is nice, so maybe we can just remove this line:

https://github.com/jrl-umi3218/jrl-cmakemodules/blob/bbdade93ad2a4b7818cb5d5b9f0bf131627e0b71/python.cmake#L248

**Comment by jmirabel** [comment]
I agree with:
- removing the line @nim65s mentioned,
- adding a warning for developpers into PYTHON_INSTALL_BUILD stating it will be removed in the future.

**Comment by jcarpent** [comment]
Fine with me too.
