### ISSUE TITLE
License switch to BSD-clause 2

### ISSUE THREAD

**Issue by olivier-stasse** [jrl-umi3218/jrl-cmakemodules#163]
Dear all,
Would you mind that we switch the license to BSD-clause 2 which is much more business friendly.

**Comment by gergondet** [comment]
Hi Olivier,

I wouldn't mind personally.

A bit out of scope but I was actually wondering about the status of this cmake scripts recently and whether this affects anything in a project. Strictly speaking this is not part of a software source (it's merely a tool that makes the building of the software easier). Any litterature/source on the topic?

**Comment by jmirabel** [comment]
Some files are actually software source. Their license was changed some time ago: https://github.com/jrl-umi3218/jrl-cmakemodules/pull/126

**Comment by gergondet** [comment]
@jmirabel yes but the license was already changed for those. The bulk of this project is cmake (and a dash of Python) that is mostly GPL/LGPL and not included as part of the software itself

**Comment by olivier-stasse** [comment]
Therefore let us keep it as it is.
