### ISSUE TITLE
Uninstall and automatic cmake

### ISSUE THREAD

**Issue by gabrielebndn** [jrl-umi3218/jrl-cmakemodules#182]
When doing `make uninstall`, it seems `cmake .` is run. This prompts cmake to look for required package dependencies. If one of them has already been removed, the dependency will not be found and the uninstallation will fail.
Since the purpose of running `make uninstall` is to remove the package, it should not matter whether the package dependencies are there or not and the uninstallation should succeed regardless

**Comment by jmirabel** [comment]
Yes, that's annoying but hard to achieve from the current method.

A workaround if you want to move on:
```
rm -v `cat install_manifest.txt`
```

**Comment by jcarpent** [comment]
I will close this issue. @gabrielebndn Feel free to reopen it if needed.
