### ISSUE TITLE
Update to more recent CMake version

### ISSUE THREAD

**Issue by jmirabel** [jrl-umi3218/jrl-cmakemodules#188]
This is not of high priority but, for some of them, we regularly get warning messages. If relevant, I will try to update the list as I discover changes.
- [x] the project version should be passed to macro `project` (from 3.0 I think).
- [x] CMake targets of the form `boost::python` rather than providing the path.

**Comment by jcarpent** [comment]
I get the first point, but not the second point. Can you explain a bit further?

**Comment by jmirabel** [comment]
> I get the first point, but not the second point. Can you explain a bit further?

I can't since I don't know the details. I know they are called imported targets.

**Comment by jmirabel** [comment]
Use [GENERATE_EXPORT_HEADER](https://cmake.org/cmake/help/v3.0/module/GenerateExportHeader.html) to generate `config.hh`.

**Comment by jcarpent** [comment]
Since CMake 3.15, the call to the PROJECT should be done at the first lines of the root CMakeLists.txt.
See https://cmake.org/cmake/help/v3.15/command/project.html#code-injection for further explanations.

**Comment by jmirabel** [comment]
As I understand the doc, it is forbidden to call PROJECT from an included file. I think calling PROJECT inside a macro called from the root CMakeLists.txt is fine as macro are not functions.

**Comment by jcarpent** [comment]
This is currently warning on my Mac currently:
```
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by jmirabel** [comment]
So we are doomed...
