### ISSUE TITLE
pkg-config : issue with SYSTEM in include_directories

### ISSUE THREAD

**Issue by olivier-stasse** [jrl-umi3218/jrl-cmakemodules#195]
When doing include_directories here
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/pkg-config.cmake#L764
and here
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/pkg-config.cmake#L766
the SYSTEM option is used.
It forces to uses -isystem instead of -I and change the order of inclusion with the header files.
It happens to be breaking the chaining of workspace in one of our ros package.
Do you mind if we remove them or is there any particular rational behing this choice ?

**Comment by jmirabel** [comment]
From gcc man page:
> -isystem dir
>  Search dir for header files, after all directories specified by -I but before the standard system
>  directories.  Mark it as a system directory, so that it gets the same special treatment as is
>  applied to the standard system directories.  If dir begins with "=", then the "=" will be replaced
>  by the sysroot prefix; see --sysroot and -isysroot.

I usually use SYSTEM to get rid of compilation warnings which originates from headers of third party libraries. After reading the doc, I agree systematically using SYSTEM is not a good idea. The best would be to expose it.

The best way would be to use https://cmake.org/cmake/help/v3.0/module/CMakeParseArguments.html in PKG_CONFIG_USE_DEPENDENCY. It's fairly easy to use.
