### ISSUE TITLE
NO_INCLUDE_SYSTEM not working (related to #195)

### ISSUE THREAD

**Issue by olivier-stasse** [jrl-umi3218/jrl-cmakemodules#228]
Wrt to Issue #195 the option NO_INCLUDE_SYSTEM is not taken into account.
The rational is the following:
The test in https://github.com/jrl-umi3218/jrl-cmakemodules/blob/0fb087eb8e78db616329de0e4ab55abbe015bbe8/pkg-config.cmake#L779 is always true. Indeed it is testing if the variable NO_INCLUDE_SYSTEM exists or not (or if it is true or not). However as mentionned in cmake documentation macros arguments are not variables, but are used as string substitution. It should be replaced by ${NO_INCLUDE_SYSTEM}.
A PR fixing this will follow.

**Comment by jcarpent** [comment]
Solved by #229.
