### ISSUE TITLE
Call to post-project.cmake not working

### ISSUE THREAD

**Issue by jcarpent** [jrl-umi3218/jrl-cmakemodules#245]
Dear @gergondet and @jmirabel,

I'm currently passing Pinocchio to the new ordering of files (see https://github.com/stack-of-tasks/pinocchio/pull/907). But it appaers that the call to `post-project.cmake` does not work performed after call to `PROJECT(...)` thanks to https://github.com/jrl-umi3218/jrl-cmakemodules/blob/0d3bc41a305d16189089133a58a6979a318cc26d/base.cmake#L150. 
Have you encountered similar bahavior on your respective sides?

Best,

Justin

**Comment by gergondet** [comment]
Hi Justin,

You need to `include(cmake/base.cmake)` before calling `project()` and you shouldn't include `cmake/post-project.cmake` manually

I've implemented the change on many repositories today and I have had no issues (except for having to explictly tell CMake when my project mix C/C++)

**Comment by jmirabel** [comment]
Might be worth insisting on this in the doc.

Somehow related: the documentation hasn't been generated since one month although the master branch has changed. I do not have the rights to check the hooks in the settings.

**Comment by gergondet** [comment]
@jmirabel Maybe that's an issue on your side (force a refresh or check in incognito mode) but on my side I see the doc for the latest commit

**Comment by jmirabel** [comment]
I manually triggered the generation. Go here to see the list of builds: https://readthedocs.org/projects/jrl-cmakemodules/builds/

**Comment by gergondet** [comment]
Ok, I haven't changed anyside on either side but maybe something changed since we set it up.

I've set it as instructed on the doc. I think it should work...

**Comment by jcarpent** [comment]
Thanks a lot @gergondet. I did not notice the subtility.
