### ISSUE TITLE
git describe failing causes project to not compile

### ISSUE THREAD

**Issue by VladimirIvan** [jrl-umi3218/jrl-cmakemodules#253]
When git describe fails, code stops compiling as the version numbers cannot be filled in. This is the case e.g. on a new repository with branches but no tags. 

cc @wxmerkt

**Comment by jcarpent** [comment]
Small question, what is the output of `git tag`? 
In fact, the module is looking for the current version of the project either in the file named `.version`in the root directory of the project or inside the git tree (a tag to be more precise).

**Comment by jmirabel** [comment]
I think I already encountered a similar issue. I solved it be setting PROJECT_VERSION in the CMakeLists.txt.
IMHO: The git describe message is only a warning and the issue you encounter comes either from #242 or #221

**Comment by jcarpent** [comment]
So if you put the tags on the fork, it should work. But maybe, you do not want to?

**Comment by wxmerkt** [comment]
Yes, putting the tags makes it work. It would be good if not having tags or requiring a repository was handled gracefully. For instance, some workflows (including the buildfarm) involve downloading the tar.gz archive which by nature isn't a git repository.

**Comment by jcarpent** [comment]
Sure. Normally, the package generated by the jrl cmake module is taking care for the generation of the `.version`file to get the value.

**Comment by jmirabel** [comment]
> Yes, putting the tags makes it work. It would be good if not having tags or requiring a repository was handled gracefully. For instance, some workflows (including the buildfarm) involve downloading the tar.gz archive which by nature isn't a git repository.

That archive should contain a `.version` file at the root.

**Comment by jmirabel** [comment]
I don't think #258 changes anything to this.

**Comment by jcarpent** [comment]
This is is not an archive, but an issue of git tree. See #258 for more details.

**Comment by wxmerkt** [comment]
> That archive should contain a .version file at the root.

I see neither pinocchio nor eigenpy including `.version` files.

**Comment by jcarpent** [comment]
It is present in the tar.gz of the releaes ;à

**Comment by wxmerkt** [comment]
I see. Is it manually added? People who download master/devel as a zip-ball per github wont get it though as it's not checked in, correct?

**Comment by jcarpent** [comment]
It is added by the command 'make release VERSION=x.y.z` of the submodule. It will create a tar.gz with all the submodules of git integrated, as by default the packager of GitHub is doing this job.

**Comment by olivier-stasse** [comment]
Please do not add it by hand. It is a pain to maintain the consistency.  Having it with package.xml is already redundant but I think the benefits outperform the disadvantages. I prefer that you maintain your pressure in having people releasing often and add tags. This is I think the proper way to follow the evolution of the codes.
