### ISSUE TITLE
Finding boost throws warnings

### ISSUE THREAD

**Issue by wxmerkt** [jrl-umi3218/jrl-cmakemodules#259]
Searching for Boost(Python) throws CMake warnings. I noticed `boost.cmake` uses a custom script to search for Boost. Is it possible to use CMake's native `FindBoost.cmake` (in newer version) or to include it in `find-external` (for backward compatibility)?

**Comment by jcarpent** [comment]
This is indeed a good idea. I have changed the behavior of the search to silent the warnings.
Currently, the current jrl-cmake uses the FindBoost.cmake searched by cmake.
The current main function `SEARCH_FOR_BOOST` only tries to look for the correct Python version of Boost.Python according to the OS (it could be python27, python3, etc.). 

So, what is your point on using directly the FindBoost.cmake? I did not get it :(

**Comment by jcarpent** [comment]
@wxmerkt Did you remove the CMakeCache.txt. The QUIET option should silent the warnings, isn't it?

**Comment by wxmerkt** [comment]
Yes, I made a full clean and it still shows as warnings as above

**Comment by jcarpent** [comment]
It seems the message is print out by the script FindBoost.cmake, we cannot do more.

**Comment by wxmerkt** [comment]
We can include a more recent `FindBoost.cmake` inside `find-external`

**Comment by jcarpent** [comment]
OK. We still need to be able to check from the default system one, no?

**Comment by wxmerkt** [comment]
If we include a newer version `FindBoost.cmake` this takes the place of the system provided one. it is common with CMake to provide newer Findsomething scripts to handle updates/newer versions without requiring an update of the system-provided CMake. 

I tried the latest FindBoost but it didn't work on 18.04 - it required quite a few other new scripts. An intermediate newer version may work out of the box - I haven't had time to check which one yet.

**Comment by jcarpent** [comment]
Solved by #328.
