### ISSUE TITLE
CMake warning about CMP0007

### ISSUE THREAD

**Issue by jmirabel** [jrl-umi3218/jrl-cmakemodules#283]
This line
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/8e01cbbb07722838d69d098ae6abb4211fae1737/cmake_uninstall.cmake.in#L17

added by #52 generates the following warning
> CMake Deprecation Warning at cmake/cmake_uninstall.cmake:17 (cmake_policy):
> The OLD behavior for policy CMP0007 will be removed from a future version of CMake.
>
> The cmake-policies(7) manual explains that the OLD behaviors of all policies are deprecated and that a policy should be set to OLD only under specific short-term circumstances.  Projects should be ported to the NEW behavior and not rely on setting a policy to OLD.

I think adding `LIST(REMOVE_ITEM files "")` after 
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/8e01cbbb07722838d69d098ae6abb4211fae1737/cmake_uninstall.cmake.in#L35
should be sufficient.

**Comment by jcarpent** [comment]
@jmirabel You can proceed I think. No?
