### ISSUE TITLE
COMPUTE_PROJECT_ARGS is broken

### ISSUE THREAD

**Issue by gergondet** [jrl-umi3218/jrl-cmakemodules#296]
Using `minimal-hpp.cmake`

```
cmake_minimum_required(VERSION 2.8)

# These variables have to be defined before running SETUP_PROJECT
set(PROJECT_NAME hpp-project-example)
set(PROJECT_DESCRIPTION "A HPP project example")

# hpp.cmake includes base.cmake.
include(cmake/hpp.cmake)

COMPUTE_PROJECT_ARGS(PROJECT_ARGS LANGUAGES CXX)
message("PROJECT_ARGS: ${PROJECT_ARGS}")
project(${PROJECT_NAME} ${PROJECT_ARGS})

# Configure the build of your project here
# add_subdirectory(src)
```

The variable is empty. This can lead to weird CMake behaviours (I'm not using it myself but I encountered strange errors in CI with hpp-spline for example) and probably doesn't set everything as you'd expect.

The problem lies in the way `CMAKE_PARSE_ARGUMENTS` is called . The correct invokation should be:

```
COMPUTE_PROJECT_ARGS(VARIABLE PROJECT_ARGS LANGUAGES CXX)
```

However, this also errors because the implementation is broken.

@nim65s @jmirabel @jcarpent I guess this affects all the project where you have started using this...

This is easy to fix but we have two options:
1. Fix only the implementation and expect consumer to call the macro correctly
2. Fix the implementation and make the call that is currently documented work

I think (2) is better and I can send a PR for it quickly

**Comment by nim65s** [comment]
Well, it was working well for me, as I was able to make many source releases with it. I'm currently checking everything on different platforms before making binary releases, so I'll report any issue that I may find in the process.

**Comment by gergondet** [comment]
It's not working well, it's working by accident :)

What you end up with in the current version is:
```
project(${PROJECT_NAME})
```
which is fine except when it's not.

On a system with:
- Debian wheezy (yup)
- CMake 3.5 binary release from KitWare
- Latest Eigen installed from source

I am unable to configure hpp-spline because it cannot find Eigen3 unless the language argument is specified. I haven't look deeper why it's broken in that setup but it is.

**Comment by nim65s** [comment]
I also got an issue with that, and fixed it in https://github.com/nim65s/hpp-spline/commit/f3662026bd5e945966139912ac6b30531da80d03 so I'm not sure this is related.

But yes, everything could be working by accident, and and I nothing against your fix :)

**Comment by nim65s** [comment]
My commit fixed hpp-spline in Arch, but not in Fedora. I'm trying with your PR :)

**Comment by nim65s** [comment]
btw, I don't know why you need hpp-spline, but it is obsolete, and should be replaced by https://github.com/loco-3d/curves ; I am still maintaining it because we did not make the replacement everywhere yet, but that's all.
