### ISSUE TITLE
Make reinstall

### ISSUE THREAD

**Issue by gabrielebndn** [jrl-umi3218/jrl-cmakemodules#298]
When doing `make install`, the old version is kept there (particularly for the SOT): the new version is simply added next to the old version and then the symlinks are updated (see https://github.com/jrl-umi3218/jrl-cmakemodules/issues/189).

As an alternative to the propositions in https://github.com/jrl-umi3218/jrl-cmakemodules/issues/189 (which were ultimately rejected) I propose the following: an additional target `make reinstall` which will just run `make uninstall` first and then `make install`. This simple shortcut should ease the development.

Would you agree on that?

**Comment by jcarpent** [comment]
Yes, should be fine. Can you handle it?

**Comment by gabrielebndn** [comment]
Really busy at the moment, but I can give it a shot, it should be easy
