### ISSUE TITLE
Why config.h in the root of the build tree?

### ISSUE THREAD

**Issue by jcarpent** [jrl-umi3218/jrl-cmakemodules#300]
I do not really understand the existence of such a file **config.h** at the root of the build tree. Is there any real reason other than 'polluting' the root of the build tree? Do some packages are relying on it as it is not installed?

https://github.com/jrl-umi3218/jrl-cmakemodules/blob/2a9086eaf5e7ef7cd6992e0fd6c6c615c0893400/header.cmake#L121

**Comment by jmirabel** [comment]
I could find a few of them without knowing if it is avoidable. Did you encounter any problem with it ?
