### ISSUE TITLE
`$<CONFIGURATION>` use in uninstall.cmake

### ISSUE THREAD

**Issue by nim65s** [jrl-umi3218/jrl-cmakemodules#305]
Hi,

In #301, there is a  `$<CONFIGURATION>`:
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/349e9bcac4a3006b61d5eff2956d3cf2f3595dce/uninstall.cmake#L42

According to [CMake docs](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#id2), this is deprecated since CMake 3.0, and we should use `$<CONFIG>`.

And I don't understand what this is meant to do. In the docs, I can only find examples with eg. `$<CONFIG:Debug>`, but in my CMake 3.10.2 (18.04), it works only with `CONFIG` and not `CONFIGURATION`.

Also, in CMake 2.8.12 (14.04), the current version fails at configure time with:
```
CMake Error in CMakeLists.txt:
Evaluation file
"…/eigenpy-1.6.12/cmake/Release/cmake_reinstall.cmake"
cannot be written.
```

**Comment by gergondet** [comment]
```
And I don't understand what this is meant to do. In the docs, I can only find examples with eg. $<CONFIG:Debug>, but in my CMake 3.10.2 (18.04), it works only with CONFIG and not CONFIGURATION.
```

`$<CONFIG>` and `$<CONFIG:Debug>` are two different things. The first is what you linked to, the second is in the [Variable Queries](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#variable-queries) section so they have very different outputs. I'm doing stuff with `$<CONFIGURATION>` in very recent CMake version (3.15/3.16) and it works fine.

For the error with CMake 2.8.12, does it work if you create the directory before-hand? If so then we should do this as well (if we want to keep 2.8.12 compatibility)

**Comment by nim65s** [comment]
Adding `FILE(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/cmake/$<CONFIGURATION>")` before the this `FILE(GENERATE…` doesn't work, but a `mkdir` does.

**Comment by jmirabel** [comment]
From the documentation, it seems that only `FILE(GENERATE ...)` supports generator expressions. So `FILE(MAKE_DIRECTORY ...)` with generator expressions will not work.

Try with
```
 add_custom_target(make_dir)
 add_custom_command(TARGET make_dir POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E make_directory "${PROJECT_BINARY_DIR}/cmake/$<CONFIGURATION>")
```

**Comment by nim65s** [comment]
It doesn't work. I guess this is because this custom command is for build time, while the issue currently arise at configuration time.

**Comment by gergondet** [comment]
Yes it won’t work. I’ve fixed a similar issue in the Cython module see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/349e9bcac4a3006b61d5eff2956d3cf2f3595dce/cython/cython.cmake#L75
