### ISSUE TITLE
Cyclic symlink in cmake->_unittests->cmake

### ISSUE THREAD

**Issue by blackliner** [jrl-umi3218/jrl-cmakemodules#306]
Hi, i am trying to use eigen-qld within a bazel-built project (by using [rules_foreign_cc](https://github.com/bazelbuild/rules_foreign_cc)'s cmake_external) and bazel crashes because of that symlink cycle.

Is that symlink absolutely necessary? Cheers

**Comment by gergondet** [comment]
Thanks for reporting this.

It's only used as part of the project's CI so it should be fine to remove it if it's created by the corresponding action. Would you have time to propose a PR for that?

**Comment by blackliner** [comment]
I'll give my best :D

**Comment by blackliner** [comment]
Done

**Comment by blackliner** [comment]
Done, added the following to the CI script>
`ln -s .. cmake`

**Comment by gergondet** [comment]
Closed by #307
