### ISSUE TITLE
Python default behaviour changed - breaking builds

### ISSUE THREAD

**Issue by wxmerkt** [jrl-umi3218/jrl-cmakemodules#324]
Hi, the recent changes to this module changed the default Python version that is being found on LTS systems. 

E.g. downstream issue:
- CI on 18.04 is configured to use python 2.7.17 by default
- The recent update make it find Python3 first rather than the default configured python interpreter
- Cf. https://github.com/loco-3d/crocoddyl/commit/cf179f7bcd676cc8a489add1e83f4c031c9f09d0

**Comment by wxmerkt** [comment]
This also broke the master on eigenpy. On a fresh install of Ubuntu 18.04 it picks up `PYTHON_EXECUTABLE` as python3 even though system default is python2. This breaks builds unless the Python version is explicitly specified.

**Comment by jcarpent** [comment]
This should be definitively solved by #326.

**Comment by jcarpent** [comment]
Solved by #326.
