### ISSUE TITLE
SEARCH_FOR_BOOST broken in 16.04

### ISSUE THREAD

**Issue by nim65s** [jrl-umi3218/jrl-cmakemodules#333]
Hi again,

Updating the submodule on another project yielded the following on 16.04 (CMake 3.5.1, Boost 1.58.0):
```
CMake Error at cmake/boost.cmake:71 (IF):
if given arguments:

"105800" "VERSION_GREATER_EQUAL" "1.70"

Unknown arguments specified
Call Stack (most recent call first):
CMakeLists.txt:31 (SEARCH_FOR_BOOST)
```

I think @DianeBury & @florent-lamiraux already got this issue, but this was not reported here. This is probably a regression following #328, #329 or #330.

**Comment by jcarpent** [comment]
#336 has solved the issue, which are due to change of formatting in Boost.

**Comment by nim65s** [comment]
Indeed, that's fixed, thanks a lot !
