### ISSUE TITLE
Minimal CMake version

### ISSUE THREAD

**Issue by nim65s** [jrl-umi3218/jrl-cmakemodules#338]
Hi,

Configuring hpp-fcl on Debian 8 (oldoldstable) with CMake 3.0.2 raises the following error:
```
CMake Error at cmake/GNUInstallDirs.cmake:128 (cmake_policy):
Policy "CMP0054" is not known to this version of CMake.
Call Stack (most recent call first):
cmake/post-project.cmake:7 (INCLUDE)
CMakeLists.txt:70 (PROJECT)
```

So I think we can either:
1. Decide that we require CMake >= 3.1
2. Fix this

As this has been here for some time and nobody complained yet, I'm in favor of the first solution :)

**Comment by jcarpent** [comment]
Big step forwards if we decide to only support cmake >= 3.1. How it will behave on robotpkg? Which distributions are now outdated?

**Comment by nim65s** [comment]
Actually, I found this error message in the only distribution failing on hpp-fcl on robotpkg, and that's Debian 8: http://robotpkg.openrobots.org/rbulk/robotpkg/path/hpp-fcl/index.html#hpp-fcl-1.3.0.

CentOS 7 is also outdated, but this was already filtered out because this is not even 3.0

**Comment by gergondet** [comment]
I came across this today which might be helpful to determine the lowest cmake version required on your projects: https://github.com/nlohmann/cmake_min_version

**Comment by olivier-stasse** [comment]
Dear all,
On Focal/18.04 the cmake release version is 3.10 and its EOL is 2023. Thus I propose that it becomes the minimal version for cmake below which we do not support jrl-cmakemodules.
