### ISSUE TITLE
Calling FINDPYTHON in several CMakeLists.txt makes detection  fail

### ISSUE THREAD

**Issue by florent-lamiraux** [jrl-umi3218/jrl-cmakemodules#354]
I have spent a few hours trying to understand why in a given package python was not detected properly while in other packages it was.

I finally discovered that FINDPYTHON was also called in subdirectories.

I think it would be worth detecting this error. A simple solution would be to define a variable called `FINDPYTHON_ALREADY_CALLED` in macro `FINDPYTHON` in python.cmake and to check that this variable has not been not already defined when calling `FINDPYTHON`.

**Comment by jcarpent** [comment]
Solved by #355.
