### ISSUE TITLE
Automatically set CMAKE_BUILD_TYPE?

### ISSUE THREAD

**Issue by wxmerkt** [jrl-umi3218/jrl-cmakemodules#359]
If a project or workspace does not set `CMAKE_BUILD_TYPE`, does it make sense to automatically set it to `Release` in the project finalize callback?

**Comment by jmirabel** [comment]
This may be surprising to people who know what they do (robotpkg sets the CMAKE_CXX_FLAGS to whatever it likes and do not use CMAKE_CXX_FLAGS_<type>. Setting the build type will add more flags). Moreover, this adds one more difference with CMake.

Although it most scenario, no CMAKE_BUILD_TYPE is an omission, I would not do this.

**Comment by nim65s** [comment]
It looks like @cmastalli likes to do so: https://github.com/loco-3d/crocoddyl/commit/c346158fe8adca2f2f4c4749db8b9ee46526dab6#diff-af3b638bc2a3e6c650974192a53c7291R29

I'd be in favor of (by priority order):
1. have the same behavior in all our projects
2. have a minimal number of lines to maintain
3. when we add unnecessary lines, explicit why.

@wxmerkt issue here and @cmastalli comment in crocoddyl are not explicit enough for me: please explain why you want / need that.

I'm not saying that you're wrong, I'm saying that everything works well without, so if you don't have a reason to add that, we should remove it.

**Comment by cmastalli** [comment]
My reason is easiness. First of all, I agree with @wxmerkt that the default build compilation should be `Release`, most people want to just compile the project in `Release` mode, and some of them are not good enough with cmake flags.

Additionally, I like to press `enter` and move between different build types. It avoids to write a wrong keyword.

Despite that I included it in Crocoddyl, I am not sure if this is a feature that everyone might need / want. But certainly, I don't think it hearts, right?

**Comment by jmirabel** [comment]
> But certainly, I don't think it hearts, right?

Changing the policy will hurt for sure.

**Comment by jcarpent** [comment]
To be honest, I think keeping the default mode of CMake is safer and makes people think twice. 
The default mode is the only one that reveals the real bugs thanks to asserting.
We can add a message inside each project to mention that the current project is compiled in Debug mode. But I would not recommend to set the Release to be the default one in Crodcoddyl, which eavely relies on Eigen assert for easy debuging.
