### ISSUE TITLE
Failed to detect Numpy on Debian Buster

### ISSUE THREAD

**Issue by wxmerkt** [jrl-umi3218/jrl-cmakemodules#373]
This is from a failing CI job on Debian Buster for EigenPy (Ubuntu Focal is just fine):

The following packages have been installed:
```
apt-get install -y -qq git
apt-get install -y -qq doxygen
apt-get install -y -qq python3-dev
apt-get install -y -qq python3-numpy
apt-get install -y -qq libeigen3-dev
apt-get install -y -qq libboost-all-dev
```

Here's information on the package: https://packages.debian.org/buster/python3-numpy

And configuration fails with
```
CMake Error at cmake/python.cmake:475 (MESSAGE):
  Failed to detect numpy
Call Stack (most recent call first):
  CMakeLists.txt:57 (FIND_NUMPY)
```

**Comment by nim65s** [comment]
eigenpy 2.3.0 works well on Debian 10 "Buster" on robotpkg: http://robotpkg.openrobots.org/rbulk/robotpkg/math/py-eigenpy/

**Comment by nim65s** [comment]
And this works too:

```
FROM debian:buster

RUN apt-get update && apt-get install -qqy \
    build-essential cmake git doxygen \
    python3-dev python3-numpy \
    libeigen3-dev libboost-all-dev

ARG EIGENPY_VER=2.3.2
ADD https://github.com/stack-of-tasks/eigenpy/releases/download/v${EIGENPY_VER}/eigenpy-${EIGENPY_VER}.tar.gz /
RUN tar xvf /eigenpy-${EIGENPY_VER}.tar.gz

WORKDIR /build

RUN cmake -DPYTHON_EXECUTABLE=$(which python3) /eigenpy-${EIGENPY_VER}
RUN make -j12
RUN make test
RUN make install
```

So I guess your issue comes from elsewhere.

**Comment by wxmerkt** [comment]
Not quite - if you omit `-DPYTHON_EXECUTABLE=$(which python3)` in the above `cmake` command with the same Dockerfile, it fails:

```Dockerfile
FROM debian:buster

RUN apt-get update && apt-get install -qqy \
    build-essential cmake git doxygen \
    python3-dev python3-numpy \
    libeigen3-dev libboost-all-dev

ARG EIGENPY_VER=2.3.2
ADD https://github.com/stack-of-tasks/eigenpy/releases/download/v${EIGENPY_VER}/eigenpy-${EIGENPY_VER}.tar.gz /
RUN tar xvf /eigenpy-${EIGENPY_VER}.tar.gz

WORKDIR /build

# RUN cmake -DPYTHON_EXECUTABLE=$(which python3) /eigenpy-${EIGENPY_VER}
RUN cmake /eigenpy-${EIGENPY_VER}
RUN make -j12
RUN make test
RUN make install
```

**Comment by jcarpent** [comment]
You have to unset the PYTHONPATH if defined.

**Comment by jcarpent** [comment]
@nim65s Could you provide a docker file?

**Comment by wxmerkt** [comment]
Okay, that still means the default configuration option of `cmake ..` without extra arguments is not working for Debian Buster.

**Comment by nim65s** [comment]
It is working. Buster has python 2 by default.

```
FROM debian:buster

RUN apt-get update && apt-get install -qqy \
    build-essential cmake git doxygen \
    python-dev python-numpy \
    libeigen3-dev libboost-all-dev

ARG EIGENPY_VER=2.3.2
ADD https://github.com/stack-of-tasks/eigenpy/releases/download/v${EIGENPY_VER}/eigenpy-${EIGENPY_VER}.tar.gz /
RUN tar xvf /eigenpy-${EIGENPY_VER}.tar.gz

WORKDIR /build

RUN cmake /eigenpy-${EIGENPY_VER}
RUN make -j12
RUN make test
RUN make install
```

**Comment by nim65s** [comment]
@jcarpent dockerfiles for python 2 & python 3 are available above. do you need anything else ? or a docker image ?

**Comment by nim65s** [comment]
@wxmerkt or maybe do you expect that if you install only python 3 on a distro which has python 2 by default, this cmake module will use python 3 in the default configuration ?

**Comment by wxmerkt** [comment]
> @wxmerkt or maybe do you expect that if you install only python 3 on a distro which has python 2 by default, this cmake module will use python 3 in the default configuration ?

Good point, I don't work with Debian directly so didn't realise it still defaults to Python 2, and of course I didn't install python2-numpy.
