### ISSUE TITLE
ADD_PROJECT_DEPENDENCY: Some variables are not defined anymore

### ISSUE THREAD

**Issue by florent-lamiraux** [jrl-umi3218/jrl-cmakemodules#379]
Macro ADD_REQUIRED_DEPENDENCY("pkg") defines variables
- PKG_PREFIX, PKG_INCLUDEDIR, PKG_LIBDIR, PKG_PKGLIBDIR, PKG_BINDIR, PKG_DATAROOTDIR, PKG_PKGDATAROOTDIR, PKG_DOCDIR, PKG_DOXYGENDOCDIR.
It seems that macros ADD_PROJECT_DEPENDENCY does not. Is there an alternative to reconstruct  those variables?

**Comment by jmirabel** [comment]
What do you want to do ?

**Comment by florent-lamiraux** [comment]
I think it would be useful to have access again to these variables, but I have no idea about the effort needed.

**Comment by nim65s** [comment]
ref #268

**Comment by jmirabel** [comment]
I don't think we should add them unless we explicit a need for this that cannot be covered by standard CMake.

**Comment by nim65s** [comment]
1. everything about include dirs, lib dirs, or bin dirs is now useless if we properly use exports
2. doc dirs are already covered by #268
3. we are lacking data root dirs, and I actually have a [dirty workaround](https://github.com/humanoid-path-planner/hpp-corbaserver/blob/d050494a42af7f8d833c1eb39ac7a43cc17eec66/CMakeLists.txt#L79) waiting to be cleaned…
4. I don't think prefix is useful if we have the others

**Comment by florent-lamiraux** [comment]
For instance, how can I recover file `lib/cmake/hpp-corbaserver/ominidl.cmake` installed by `hpp-corbaserver` ?

**Comment by jmirabel** [comment]
File hpp-corbaserverConfig.cmake should either give you the path to this file or include it (so that you don't have to do it explicitely.

**Comment by olivier-stasse** [comment]
I think that this issue can be closed. @florent-lamiraux feel free to re-open it if needed.
