### ISSUE TITLE
Default version

### ISSUE THREAD

**Issue by nim65s** [jrl-umi3218/jrl-cmakemodules#381]
Hi,

Since #282, when we create a new project, we get the following error:
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
CMake Error at CMakeLists.txt:18 (PROJECT):
  VERSION ".." format invalid.
```

So I think `VERSION_COMPUTE` is supposed to always output a valid version number. And in a new project without tags, without version dotfile, and without package.xml, we don't have one.

So I think we can either:
- [use 0.1.0 as default](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)
- explain to the user that we require a version
- stop requiring a version number.

I suggest to go for the first choice.

**Comment by jcarpent** [comment]
Why not using 0.0.0?

**Comment by nim65s** [comment]
done
