### ISSUE TITLE
Alternative way of packaging for Windows

### ISSUE THREAD

**Issue by jcarpent** [jrl-umi3218/jrl-cmakemodules#390]
Currently, we are mixing both pkg-config and more classic CMake approach for exporting our libraries. It may appear at some point that on Windows systems, pkg-config is not well supported.

@gergondet Do you know some alternative to it? How do you handle projects that make use of pkg-config?

This issue is appearing as we are porting Pinocchio to Windows with @francois-keith

**Comment by nim65s** [comment]
I think we can provide pkg-config stuff for retro-compatibility, but we should focus on using only CMake exports.

I think all Gepetto projects are now working without pkg-config. And as I stopped testing build anything with pkg-config, it is probably broken until someone with an actual need for it raise an issue about it.

**Comment by gergondet** [comment]
I've ported all our libraries to the CMake approach and I simply don't bother with pkg-config support anymore. On Windows it never worked really well anyway. It was mostly fine with jrl-cmakemodules projects but not-so-much with third parties (typically: not installing the .pc at all on Windows or outputting wrong flags for MSVC, it was a mess).

In my case, all dependencies that I need work well with CMake, except for older versions but that's usually only a problem on Linux distributions that have those older versions. However, in Windows it's much easier to simply require a recent version with a working CMake interface.

**Comment by jcarpent** [comment]
Thanks a lot @gergondet for this quick and useful reply.

**Comment by jcarpent** [comment]
@gergondet Another small question is how do you handle Eigen3 find procedure on Windows?

**Comment by gergondet** [comment]
@jcarpent it's not Windows specific (for the most part)

```cmake
find_package(Eigen3 QUIET NO_CMAKE_PACKAGE_REGISTRY)
if(Eigen3_FOUND)
  add_project_dependency(Eigen3 REQUIRED NO_CMAKE_PACKAGE_REGISTRY)
else()
  add_project_dependency(Eigen3 MODULE REQUIRED)
endif()

# Later
if(TARGET Eigen3::Eigen)
  target_link_libraries(MyLib PUBLIC Eigen3::Eigen)
else()
  target_include_directories(MyLib SYSTEM PUBLIC "${EIGEN3_INCLUDE_DIR}")
endif()
```

I'm using the fallback to `MODULE` (and lack of `Eigen3::Eigen` target) for older Eigen versions (they ship with a `FindEigen3.cmake` but no `Eigen3Config.cmake`). The `NO_CMAKE_PACKAGE_REGISTRY` disable that feature because it caused problem for me in Windows specifically (not sure whether this was due to a CMake bug or a misuse of the package registry feature on Eigen side but it would point to a wrong directory for Eigen includes)

**Comment by jcarpent** [comment]
Thanks @gergondet for the very clear answer. Does cmake provide a findeigen3.cmake by default? For instance, anaconda is just installing eigen, without any search support : the pkg config file is not installed and so on.

**Comment by gergondet** [comment]
@jcarpent `FindEigen3.cmake` is normally installed by Eigen, a reasonable third way to find it is to do what the `SEARCH_FOR_EIGEN()` macro does, i.e.

```
    FIND_PATH(Eigen_INCLUDE_DIR NAMES signature_of_eigen3_matrix_library
      PATHS
      ${CMAKE_INSTALL_PREFIX}/include
      PATH_SUFFIXES eigen3 eigen
    )

# Then down the line
target_include_directories(MyLib SYSTEM PUBLIC "${Eigen_INCLUDE_DIR}")
```

**Comment by jcarpent** [comment]
OK. Thanks. I think we should now rely then on FindPackage to correctly handle Windows. Thanks a lot @gergondet for sharing your feedback.
