### ISSUE TITLE
Exporting <package-name>Config.cmake files with no targets.

### ISSUE THREAD

**Issue by olivier-stasse** [jrl-umi3218/jrl-cmakemodules#398]
When having pure data package, typically robot_description kind of packages, the <package-name>Config.cmake files are very handy.
However they do not have targets. In the current writing of the SETUP_PROJECT_PACKAGE_FINALIZE macro the INSTALL( export ) calls fails because they are no targets to export.
IMHO the correct behavior is to not call this install when there is no target.

**Comment by nim65s** [comment]
Hi @olivier-stasse,

Where do you have this issue ?
All SoT packages have an  `INTERFACE` target,  eg. :

https://github.com/stack-of-tasks/tiago_data/blob/75750a1da675319f30534e3383a657e9178e8d60/CMakeLists.txt#L19

**Comment by olivier-stasse** [comment]
talos_data when gazebo is not detected.

**Comment by nim65s** [comment]
Can you please open an issue on talos-data, before working further on that topic ? This looks like https://github.com/stack-of-tasks/talos-data/pull/2 to me.

**Comment by olivier-stasse** [comment]
I respectfully disagree. jrl-cmakemodules should be able to handle package with no target.

**Comment by olivier-stasse** [comment]
But of course this is a personal opinion that should be discussed openly and I will go towards  the community decision.
Note: my solution is partial. Because Config.cmake.in impose to include Targets.cmake this later trigger an error on a package using it.

**Comment by nim65s** [comment]
I agree, jrl-cmakemodules should be able to handle package with no target. But I would like to understand the issue you are trying to solve on talos-data.

**Comment by olivier-stasse** [comment]
Fixed by PR #408
