### ISSUE TITLE
Boost 1.72

### ISSUE THREAD

**Issue by olivier-stasse** [jrl-umi3218/jrl-cmakemodules#413]
I am currently having the following problem on MacOS Catalina.
In sot-core, jrl-cmakemodules is detecting the following:
```sh
Boost_PYTHON_LIBRARY=optimized;/usr/local/lib/libboost_python38.dylib;debug;/usr/local/lib/libboost_python38-mt.dylib
```
which is then used by ```Boost_PYTHON_LIBRARIES```
here https://github.com/jrl-umi3218/jrl-cmakemodules/blob/c333a88decb3e4c0a86947bc6c7f072dc5c5df20/boost.cmake#L227

It thus creates the following option at link time
```sh
-Wl,-undefined,dynamic_lookup,optimized
```
as far as I understood optimized should be replaced by the second argument of ```Boost_PYTHON_LIBRARY```, or maybe by ```Boost_PYTHON_LIBRARY_RELEASE```if this is the mode set for ```CMAKE_BUILD_TYPE```.

Did somebody else had the problem ?

**Comment by jcarpent** [comment]
@olivier-stasse Do you still encounter this issue?

**Comment by jcarpent** [comment]
It is not appearing on my side.

**Comment by olivier-stasse** [comment]
I still have the same issue.

**Comment by olivier-stasse** [comment]
Ok. It seems that the branch topic/dynamic_graph_cp11 is missing some macros namely SET_BOOST_DEFAULT_OPTIONS in boost.cmake which, once included, provides the expected behavior.
So I guess I just have to wait that this branch gets properly merged in the master branch.

**Comment by nim65s** [comment]
I merged master into that branch this morning

**Comment by olivier-stasse** [comment]
I have seen that afterwards.
Many thanks @nim65s
