### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by jcarpent** [jrl-umi3218/jrl-cmakemodules#416]
In the following lines:

https://github.com/jrl-umi3218/jrl-cmakemodules/blob/1498ee681d9f6b83ffd231978279fe94a2fa1c25/base.cmake#L199

It seems that there are two ways using various CMake features to achieve the same task. Is it normal? Do we really need these two versions?
@jmirabel thanks in advance for your clarifications.

**Comment by gergondet** [comment]
I think the issue is that `IN_LIST` was introduced in CMake 3.3.0 and we try to support CMake >= 3.1

**Comment by jmirabel** [comment]
My intend was to make it clear what part should be removed when the minimal supported version of cmake is increased.

**Comment by jcarpent** [comment]
Because, with recent version of CMake, we have new issues related to this code, such that:
```
CMake Warning (dev) at cmake/base.cmake:203 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "_PACKAGE_CONFIG_DEPENDENCIES_PROJECTS" will no
  longer be dereferenced when the policy is set to NEW.  Since the policy is
  not set the OLD behavior will be used.
Call Stack (most recent call first):
  cmake/package-config.cmake:79 (_ADD_TO_LIST_IF_NOT_PRESENT)
  CMakeLists.txt:67 (ADD_PROJECT_DEPENDENCY)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by jmirabel** [comment]
The issue actually comes from https://github.com/jrl-umi3218/jrl-cmakemodules/blob/1498ee681d9f6b83ffd231978279fe94a2fa1c25/package-config.cmake#L79 which quotes a variable name.

Maybe using a function instead of a macro will work. Otherwise, we have the update `package-config.cmake`.

**Comment by jcarpent** [comment]
@gergondet @jmirabel Thanks for the report.
