### ISSUE TITLE
Boost::Python export on 16.04

### ISSUE THREAD

**Issue by nim65s** [jrl-umi3218/jrl-cmakemodules#422]
Hi,

Following #407, I have several errors about the fact that we export a Boost::Python dependency under a made up name.

Here is the first.

On 16.04 (CMake 3.5), I can build and install eigenpy fine with Python 3. But then, when I want to configure hpp-fcl:
```
-- eigenpy searched on  FOUND. eigenpy at /tmp/3/lib/libeigenpy.so
-- boost_python-py35 searched on  FOUND. boost_python-py35 at /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_python35

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  /tmp/3/lib/cmake/eigenpy/eigenpyConfig.cmake:123 (find_package)
  CMakeLists.txt:75 (FIND_PACKAGE)
```

Where `CMakeLists.txt:75` is `FIND_PACKAGE(eigenpy 2.2 REQUIRED)`, and `/tmp/3/lib/cmake/eigenpy/eigenpyConfig.cmake:123` is `find_package(Boost COMPONENTS python35 REQUIRED)`.

This issue is [breaking build on robotpkg](http://robotpkg.openrobots.org/rbulk/robotpkg/path/py-hpp-fcl/py35-hpp-fcl-1.4.5/Ubuntu-16.04.pal-x86_64/bulk.html)

Adding the generated `find_package(Boost COMPONENTS python35 REQUIRED)` in various places, I found that the issue is raised if this line is added before that one

https://github.com/jrl-umi3218/jrl-cmakemodules/blob/fb4c22c319ec5320f9a85527eb1a4130954846f5/boost.cmake#L61

So, should we ship this `FindBoost.cmake` ? Or do we have another solution ?
Removing Boost::Python from the exports would be a workaround too.

In any case, I think that we should ensure that the ways we find Boost and its components are the same, whether we are in the main CMakeLists.txt or in a generated xxxConfig.cmake.

**Comment by jcarpent** [comment]
I would say that we need to ship the FindBoost.cmake file together with the export. This is only way to get a consistent import.
Another fix in your case would be to first perform the FindBoost() before calling the dependencies. In this way, you will use the correct script.

**Comment by jmirabel** [comment]
If Boost Python is the only problem, then, always shipping `FindBoost.cmake` is not a good idea. Most of the software that use Boost Python do not need to export targets depending on Boost Python.

I think that not exporting Boost Python by default, and then let users handle the export of Boost Python (or provide a macro that does it) is a wiser (arbitrage between code quality/length, desired features and time spent to develop and maintain) option.

**Comment by nim65s** [comment]
Here is a way to reproduce this issue with docker:
```bash
docker run --rm -it gepetto/utils:cmake-422
# and once in the container
cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
```

([The Dockerfile is available here](https://github.com/nim65s/gepetto-utils/blob/master/docker/hpp-fcl/source.Dockerfile))

**Comment by nim65s** [comment]
I think that we never actually need to export Boost Python. But if we did (and correctly), that would avoid the need for the dependent package to take have to find it.

**Comment by jmirabel** [comment]
> I think that we never actually need to export Boost Python.

I had a doubt for eigenpy.
