### ISSUE TITLE
TARGET 'compile_pyc' was not created in this directory.

### ISSUE THREAD

**Issue by nim65s** [jrl-umi3218/jrl-cmakemodules#425]
Hi,

As noted by @proyan in https://github.com/loco-3d/crocoddyl/pull/809#issuecomment-664992804, #392 introduced a custom target, which break this macro when it is used from multiple CMakeLists.txt.

**Comment by jmirabel** [comment]
You can try to add `ADD_CUSTOM_TARGET(compile_pyc ALL)` in the top-level CMakeLists.txt. I am not sure whether targets from parent CMakeLists are accessible.

**Comment by proyan** [comment]
`ADD_CUSTOM_TARGET(compile_pyc ALL)` didn't work in top-level CMakeLists.txt.

**Comment by proyan** [comment]
I checked d7ae304 and it works for the issue https://github.com/loco-3d/crocoddyl/pull/809
