### ISSUE TITLE
support for version checking in external finders

### ISSUE THREAD

**Issue by proyan** [jrl-umi3218/jrl-cmakemodules#427]
related to: https://github.com/loco-3d/crocoddyl/pull/824/files#r465941184

Hi guys,
Is it possible to add version check in the external finders? It seems that currently version checking is not possible in the Cmake itself.

**Comment by proyan** [comment]
I'll be happy to help, if someone can show how to do the needful.

**Comment by nim65s** [comment]
The documentation to find_package is here: https://cmake.org/cmake/help/v3.1/module/FindPackageHandleStandardArgs.html
And the example about version is about this module: https://github.com/Kitware/CMake/blob/master/Modules/FindLibXslt.cmake

**Comment by proyan** [comment]
Thanks
