### ISSUE TITLE
Python: Inconsistency betwenn doc and real code

### ISSUE THREAD

**Issue by jcarpent** [jrl-umi3218/jrl-cmakemodules#433]
In the following documentation:
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/c9be6a910f566afab88797fe9952c30b3afeac2e/python.cmake#L41-L44
`PYTHON_SITELIB` is mentioned as an absolute PATH, while in reality, this is just a relative PATH.

I would suggest changing the behavior of `PYTHON_SITELIB` to be an ABSOLUTE_PATH with ${CMAKE_INSTALL_PREFIX} prepend to the current content of `PYTHON_SITELIB`. What do you think @jmirabel @nim65s @gergondet?

**Comment by nim65s** [comment]
I think we should avoid the absolute paths and use of `CMAKE_INSTALL_PREFIX` to allow relocatable builds. And everything works fine with relative paths. And if you use `-DPYTHON_SITELIB=…` with an absolute path, it will work for you too.

**Comment by jmirabel** [comment]
Fixing the doc will not break any code while fixing the code may. I would be in favor of fixing the documentation.

**Comment by jcarpent** [comment]
Perfect. I will then just change the doc accordingly.
