### ISSUE TITLE
Option to skip generation of documentation

### ISSUE THREAD

**Issue by wxmerkt** [jrl-umi3218/jrl-cmakemodules#475]
I have not found an option to skip the generation of the documentation (there is one for installation). What are your thoughts on adding an option to not generate documentation even though Doxygen is found? The use case is a development workspace where multiple packages would build documentation without need.

**Comment by nim65s** [comment]
This would be useful.

But we should also think about documentation generation / installation with other tools, and activate this or not globally, eg. for both doxygen & sphinx.

**Comment by jcarpent** [comment]
If I remember well, if you choose to not install the doc, then the doc won’t be generated.

**Comment by wxmerkt** [comment]
> If I remember well, if you choose to not install the doc, then the doc won’t be generated.

The code comments would suggest the opposite:

https://github.com/jrl-umi3218/jrl-cmakemodules/blob/3a52692a40839b10f38352c1b06ccfebc0b53f36/doxygen.cmake#L32-L35

However, I believe you are correct - while the `doc/` folder gets created and a `Doxyfile` written, I did not see output that would suggest that doxygen is actually run.

**Comment by gergondet** [comment]
Just to elaborate a little bit, what the comment hints at is that you can still do `make doc` (or something equivalent)

When `INSTALL_DOCUMENTATION` is `ON`, `make doc` is run as part of the install (and the generated files are installed). When it's `OFF` none of that happens.

**Comment by wxmerkt** [comment]
Thank you for the additional insight @gergondet - my use case is clearly covered already :-)
