### ISSUE TITLE
Catkin and distribution targets

### ISSUE THREAD

**Issue by gergondet** [jrl-umi3218/jrl-cmakemodules#48]
Hi all,

I'd like to discuss an issue (and ideally a solution to that issue) that I encountered while working with several projects that use jrl-cmakemodules (and more specifically the SETUP_PROJECT macro) and trying to build them in a catkin environment. 

When calling the SETUP_PROJECT() macro, a bunch of other macros are called, in particular, the _SETUP_PROJECT_DIST(), DISTCHECK_SETUP() and RELEASE_SETUP() macros. These macros create targets that are most useful for packaging purposes (i.e. dist\* targets and release target).

Now, the catch is that if you have multiple projects within your catkin workspace that use this macro then your build will fail at the configuration step when invoking catkin_make because it's trying to create multiple targets that share the same name which is illegal.

One work-around is to use catkin_make_isolated (see http://www.ros.org/reps/rep-0134.html). Using the appropriate option it can be invoked in a way that the output mimics the results of catkin_make but the build still occur in an isolated way for each package. However, it would be nice to be able to invoke catkin_make directly without worries.

I see two possible solutions to this problem but there may be more (and better):
1. Change the dist\* and release target names to something that depends on the project name (e.g. release-${PROJECT_NAME}). This requires very little effort but will break every scripts that are used to generate packages (e.g. jrl-umi3218/jrl-travis)
2. Don't generate these targets unless explicitly made to. This way, we require an additional arguments to have these targets generated. This makes the transition much easier for scripts that package the software (i.e. just use an additional argument when invoking cmake)

Any other solution that does not break anything would be most welcome. Alternatively it might just not make much sense to keep using SETUP_PROJECT within a catkin project.

A few more notes on the matter:
- afaik, it's not possible to redefine an existing target or even test for its existence
- it is also not possible to ignore those errors and continue onto the Makefile generation by cmake

Best,

**Comment by jcarpent** [comment]
This issue has been solved recently by #214.
