### ISSUE TITLE
Automatically incrementing package.xml version if package.xml present

### ISSUE THREAD

**Issue by wxmerkt** [jrl-umi3218/jrl-cmakemodules#483]
With Justin we have been discussing to automate incrementing/adapting the version in `package.xml` when `make release VERSION=x.y.z` is called.

The current idea is to use `_COMPUTE_VERSION_FROM_ROS_PACKAGE_XML_FILE` from `version.cmake` and if the version does not match the version given with `VERSION=` to use `sed` to amend the `package.xml` and then commit it as part of the release process. 

However, before implementing this - would love to hear some feedback if there are other thoughts / suggestions.

**Comment by jcarpent** [comment]
Solved via #484 and #485
