### ISSUE TITLE
Issues with pcfiledir

### ISSUE THREAD

**Issue by jmirabel** [jrl-umi3218/jrl-cmakemodules#566]
When trying to compile Pinocchio with hpp-fcl, I hit the following error:
```text
CMake Error at cmake/doxygen.cmake:670 (file):
  file RELATIVE_PATH must be passed a full path to the directory:
  ${pcfiledir}/../../share/doc/pinocchio/doxygen-html
Call Stack (most recent call first):
  cmake/base.cmake:316 (_setup_project_documentation_finalize)
  cmake/base.cmake:207 (setup_project_finalize)
  CMakeLists.txt:9999 (SETUP_PROJECT_FINALIZE_HOOK)
```
I guess the `pcfiledir` introduced in #519 ought to be evaluated.

When I compile without hpp-fcl, it works fine. When I compile with `INSTALL_DOCUMENTATION=OFF`, it works fine too.

**Comment by nim65s** [comment]
My bad. I don't know how this didn't trigger any tests on my side. This issue is also hitting @manifoldfr.
I'll have time for this next week.

**Comment by jcarpent** [comment]
Is this issue still valid?

**Comment by nim65s** [comment]
I didn't change anything, yet I can't reproduce it. Building and installing latest eigenpy & hpp-fcl with `-DINSTALL_DOCUMENTATION=ON` doesn't prevent me from configuring pinocchio with `-DINSTALL_DOCUMENTATION=ON`.

**Comment by jmirabel** [comment]
It's a bit old and I didn't provide enough details to reproduce the issue. Now I don't remember what I did.
Feel free to close. If it happens again, I'll open again and provide more details.
