### ISSUE TITLE
Cannot COMPUTE_VERSION_FROM_ROS_PACKAGE_XML_FILE on Windows

### ISSUE THREAD

**Issue by alxbilger** [jrl-umi3218/jrl-cmakemodules#601]
The following commands are not supported on Windows:
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/7cf918642ffff34e6960b240aae87b0414c28860/version.cmake#L124-L127

**Comment by nim65s** [comment]
#603 might provide better results
