### ISSUE TITLE
Read the doc integration

### ISSUE THREAD

**Issue by jmirabel** [jrl-umi3218/jrl-cmakemodules#636]
FYI, I received this notification from Read The Docs

> Previously, manually configured webhooks from integrations did not have a secret attached to them. In order to improve security, we have deployed an update so that all new integrations will be created with a secret, and we are deprecating old integrations without a secret. You must migrate your integration by January 31, 2024, when they will stop working without a secret.
> 
> We are contacting you because you have at least one integration that does not have a secret set. These integrations are:
> 
>     https://readthedocs.org/dashboard/jrl-cmakemodules/integrations/15002/
> 
> If you aren't using an integration, you can delete it. Otherwise, we recommend clicking on "Resync webhook" to generate a new secret, and then update the secret in your provider's settings as well. You can check [our documentation](https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html) for more information on how to do this.
> 
> You can read more information about this in our blog post: https://blog.readthedocs.com/security-update-on-incoming-webhooks/.

I do not have admin access to this repo so I can't do the second step.

**Comment by gergondet** [comment]
Hi @jmirabel 

I have done the sync, it required adding oauth access to the jrl-umi3218 organization but hopefully it should work next time.
