### ISSUE TITLE
Update Wiki and/or provide useful readme

### ISSUE THREAD

**Issue by bchretien** [jrl-umi3218/jrl-cmakemodules#66]
A list of the main features (e.g. Doxygen support) would be really helpful. Right now, people need to read the `*.cmake` files. This could be made available in the Wiki, or in the `README.md` (which would probably be smarter since this is bundled in the submodule).

**Comment by bchretien** [comment]
Another possibility would be to generate the documentation with sphinx, directly from the `*.cmake` files. This seems to be the approach followed by CMake itself (i.e. [this](https://github.com/Kitware/CMake/blob/acd8a73044e879286f0cfa24b54497a8307f204b/Modules/FindCUDA.cmake#L1-L323) leads to [that](https://cmake.org/cmake/help/v3.5/module/FindCUDA.html?highlight=findcuda)).

**Comment by jmirabel** [comment]
I tried the option mentioned above. Using `sphinx` and the `cmake.py` extension from the [cmake repo](https://gitlab.kitware.com/cmake/cmake/blob/master/Utilities/Sphinx/cmake.py), I am able to generate a doc from the cmake file by adding line:
```
#.rst:
```
before the documentation section. The documentation looks like on the link above.

If we go for this solution, the question is: where could the documentation be stored ? on a branch `gh-pages` on this repo, which a github hook to update it on each merge ?

**Comment by jmirabel** [comment]
As an example, generated from my fork, it generates this:
- http://github.com/jmirabel/jrl-cmakemodules
- http://cmake-submodule.readthedocs.io/en/latest/

Note that:
- the files that are parsed must be specified manually (see `docs/pages/external_deps.rst` for instance)
- only the macros where I added `#.rst:` are documented

**Comment by jmirabel** [comment]
> I think the documentation headline (e.g. SEARCH_FOR_EIGEN here) could include the function/macro "prototype"

Feel free to edit.

> Btw, what is the effect of the command/variable precision in the documentation? I don't see any effect on the display of the doc. I also didn't see any option documented in the example you provided. Is this is a limitation of cmake.py?

From my understanding of `cmake.py`, the only difference are:
- references to commands are case insensitive while references to variables are case sensitive;
- they appear differently in the index;
- in the HTML, they have different classes so it should not be hard customize their appearance.

> I'm also wondering if it is possible to split internals/public documentation if they originate from the same file (e.g. pkg-config.cmake has both internal and public macros that are worth documenting).

I'm not an expert of Sphinx. I added something to make it work. The file is parsed twice, with a different mode (either "user" or "internal"), which defines what is kept and what is thrown away.

**Comment by jmirabel** [comment]
I'll open a pull-request when https://github.com/jrl-umi3218/jrl-cmakemodules/pull/115 gets merged. If you have an account on https://readthedocs.io, I can add you as a maintainer.

**Comment by gergondet** [comment]
Great.

I've created an account on rtd, same name as github (i.e. `gergondet`)

**Comment by jmirabel** [comment]
I think this could be closed. I do not have the rights to do it.
