### ISSUE TITLE
Clang-Format style configuration

### ISSUE THREAD

**Issue by bchretien** [jrl-umi3218/jrl-cmakemodules#69]
cc @gergondet @galdeano @stanislas-brossette 

Since the jrl-cmakemodules are widely used in our projects, it could be interesting to bundle a (default) clang-format style configuration that people could use. Most editors also support it: Vim, Emacs, SublimeText, Visual Studio etc.

But first, we would need to agree on a proper format/coding style. A list of options is available [here](http://clang.llvm.org/docs/ClangFormatStyleOptions.html), and usually the first step is to set `BasedOnStyle` to [some famous style guide](http://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options).

Obviously, jrl-cmakemodules users would not be forced to use this, and could still decide to use their own coding style (or none at all), but this could be valuable for new projects/developers.

**Comment by stanislas-brossette** [comment]
:+1: 
Very good idea. I personally like the Google style.

**Comment by arntanguy** [comment]
+1
I usually use Google style as well.

**Comment by Galdeano** [comment]
Ok for google style

**Comment by bchretien** [comment]
My only complaint with the Google style is their bracket breaking style, I always thought the vertical consistency of Allman/BSD helped readability compared to the Java/Attach style  (you can see these differences in action [here](http://astyle.sourceforge.net/astyle.html#_Bracket_Style_Options)). Then again, clang-format is designed so that you can easily adapt any default style template easily.

**Comment by haudren** [comment]
Just to chime in: a good part of our codebase (i.e. Joris' code, and Pierre's rewrite in C++) already uses a BSD style, with brackets broken down.

**Comment by bchretien** [comment]
Then, something like this could serve as a good base:

```yaml
---
Language: Cpp
BasedOnStyle: Google
BreakBeforeBraces: Allman
...
```

**Comment by bchretien** [comment]
@olivier-stasse @florent-lamiraux any opinion on the default format for possible LAAS-related codes?

**Comment by olivier-stasse** [comment]
Well I like the google style with the BSD style for the brackets.
So it is all fine with me

**Comment by bchretien** [comment]
Since we all seem to be agreeing on this, I'm adding the default `.clang-format` to the repo.
