### ISSUE TITLE
CMAKE_CXX_FLAGS order

### ISSUE THREAD

**Issue by jmirabel** [jrl-umi3218/jrl-cmakemodules#84]
Is there a specific reason for the order in https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/compiler.cmake#L61:
```cmake
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${WARNING_CXX_FLAGS}")
```

Setting `CMAKE_CXX_FLAGS` in this order means when doing
```bash
cmake -DCMAKE_CXX_FLAGS="something"
```
some of the flags of command line can be overwritten by flags in variable `WARNING_CXX_FLAGS`. Is this a desired behaviour ? Is there a problem with the following reordering:
```cmake
SET(CMAKE_CXX_FLAGS "${WARNING_CXX_FLAGS} ${CMAKE_CXX_FLAGS}")
```
?

**Comment by bchretien** [comment]
I don't think so, we just usually append flags. Extra user-defined flags rarely concern warnings, since this is something tackled at the project level.

**Comment by jmirabel** [comment]
Just to make sure I understand your answer: you mean the current behaviour, as opposed to the one I propose, is preferable ?

**Comment by bchretien** [comment]
No, I was just trying to find an explanation as to why this has been like this for years without that ever being an issue ;) What was the actual problem? Trying to disable one of the warnings set by the `jrl-cmakemodules` directly from the user-defined CMake variables?

Your fix should not break anything, so I don't see the harm in making that change.

**Comment by jmirabel** [comment]
Yes, I was trying to disable some warnings from the cmake command line. When installing some dependencies on travis, the build is stopped because the log (full of warnings) is too long...
I have workarounds in mind for this problem, like resolving the underlying issue, but I think command line arguments should predominate over the rest.

PS: I do not have write access to the repo so I cannot do the merge myself.

**Comment by bchretien** [comment]
I see, we often enable `-Werror` so that never happened with RobOptim for example, but this could happen to some other projects. PR merged, thanks!

**Comment by jmirabel** [comment]
Thanks for your quick replies.
